### ISSUE TITLE
"Max retries exceeded" aborts script

### ISSUE THREAD

**Issue by danstoner** [danstoner/dailymile_export#7]
When hitting the "Max retries" limit on the dailymile API, the export script aborts completely without writing the current data to the output file.  Should instead write out what we have succeeded in downloading.

Traceback (most recent call last):
  File "dailymile_export_to_csv.py", line 131, in <module>
    r = s.get(api_url_entries)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.dailymile.com', port=443): Max retries exceeded with url: /people/danstoner/entries.json?page=3414 (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

**Comment by danstoner** [comment]
Fix should be included since
https://github.com/danstoner/dailymile_export/commit/ce2b5927f811408f4206d340dd91cc4eed853f2f
